name: Deployment Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint
        continue-on-error: true
      
      - name: Build project
        run: npm run build -- --no-lint
      
      - name: Start dev server
        run: |
          npm run dev &
          DEV_PID=$!
          echo "Dev server started with PID: $DEV_PID"
          
          # Wait for dev server to be ready
          echo "Waiting for dev server to start..."
          for i in {1..30}; do
            if curl -f http://localhost:3000 > /dev/null 2>&1; then
              echo "Dev server is responding!"
              kill $DEV_PID
              exit 0
            fi
            echo "Attempt $i: Server not ready yet..."
            sleep 2
          done
          
          echo "Dev server failed to start within timeout"
          kill $DEV_PID
          exit 1
